version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: country-app-client
    container_name: country-app-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
